-- ============================================================
-- CodePolice — Supabase Schema
-- Version : 1.1.0  (added github_user to all tables)
-- Created : 2026-02-20
-- ============================================================
-- Run this file ONCE on a fresh Supabase project.
-- Tables are created with IF NOT EXISTS guards so re-runs are safe.
-- All timestamps are stored in UTC (TIMESTAMPTZ).
-- ============================================================

-- Required extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────
-- 1. WORKSPACES
--    One row per VS Code workspace window.
--    "path" is the absolute fs path of the workspace root.
--    Scoping all other data through workspace_id ensures
--    complete isolation between windows.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS workspaces (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    path         TEXT        NOT NULL,
    name         TEXT        NOT NULL,
    github_user  TEXT        NOT NULL DEFAULT 'aryasentry',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT workspaces_path_unique UNIQUE (path)
);

COMMENT ON TABLE  workspaces         IS 'One row per VS Code workspace root. Isolated by absolute path.';
COMMENT ON COLUMN workspaces.path    IS 'Absolute filesystem path, normalised to forward slashes, lowercase.';
COMMENT ON COLUMN workspaces.name    IS 'Human-readable display name — last path segment.';

-- ─────────────────────────────────────────────────────────────
-- 2. TASKS
--    The active "ticket" or goal a developer is working on.
--    Only ONE task can be active per workspace at a time,
--    enforced by the partial unique index below.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tasks (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id   UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    task_key       TEXT        NOT NULL,
    description    TEXT        NOT NULL,
    github_user    TEXT        NOT NULL DEFAULT 'aryasentry',
    is_active      BOOLEAN     NOT NULL DEFAULT true,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deactivated_at TIMESTAMPTZ,

    CONSTRAINT tasks_workspace_key_unique UNIQUE (workspace_id, task_key)
);

-- Only one ACTIVE task per workspace at any time
CREATE UNIQUE INDEX IF NOT EXISTS tasks_one_active_per_workspace_idx
    ON tasks (workspace_id)
    WHERE is_active = true;

COMMENT ON TABLE  tasks              IS 'Developer tasks/tickets. One active per workspace.';
COMMENT ON COLUMN tasks.task_key    IS 'Short identifier, e.g. FEAT-001. Must be unique per workspace.';
COMMENT ON COLUMN tasks.is_active   IS 'Only one row with is_active=true per workspace_id (enforced by partial index).';

-- ─────────────────────────────────────────────────────────────
-- 3. FILE_CHANGES
--    One row per batch-processing cycle per file.
--    Captures the raw diff and metadata.
--    file_path is stored RELATIVE to the workspace root.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS file_changes (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    task_id       UUID        REFERENCES tasks(id) ON DELETE SET NULL,
    github_user   TEXT        NOT NULL DEFAULT 'aryasentry',
    file_path     TEXT        NOT NULL,
    file_hash     TEXT        NOT NULL,
    diff_content  TEXT,
    change_cycle  INTEGER     NOT NULL DEFAULT 1,
    is_new_file   BOOLEAN     NOT NULL DEFAULT false,
    processed_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS file_changes_workspace_idx    ON file_changes (workspace_id);
CREATE INDEX IF NOT EXISTS file_changes_task_idx         ON file_changes (task_id);
CREATE INDEX IF NOT EXISTS file_changes_processed_at_idx ON file_changes (processed_at DESC);
CREATE INDEX IF NOT EXISTS file_changes_file_path_idx    ON file_changes (workspace_id, file_path);

COMMENT ON TABLE  file_changes               IS 'One row per batch processing cycle per file.';
COMMENT ON COLUMN file_changes.file_path     IS 'Path relative to workspace root, forward slashes.';
COMMENT ON COLUMN file_changes.diff_content  IS 'Unified diff. NULL for binary files or read errors.';
COMMENT ON COLUMN file_changes.change_cycle  IS 'Monotonically increasing per file within a workspace.';

-- ─────────────────────────────────────────────────────────────
-- 4. CHANGE_DESCRIPTIONS
--    LLM-generated description of each file change.
--    Generated by Ollama (qwen3-vl:235b-cloud) via the
--    description server. One row per successful Ollama call.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS change_descriptions (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    file_change_id  UUID        NOT NULL REFERENCES file_changes(id) ON DELETE CASCADE,
    workspace_id    UUID        NOT NULL REFERENCES workspaces(id)   ON DELETE CASCADE,
    task_id         UUID        REFERENCES tasks(id) ON DELETE SET NULL,
    github_user     TEXT        NOT NULL DEFAULT 'aryasentry',
    model           TEXT        NOT NULL DEFAULT 'qwen3-vl:235b-cloud',
    summary         TEXT        NOT NULL,
    classification  TEXT        NOT NULL
        CHECK (classification IN (
            'feature', 'bugfix', 'refactor', 'test', 'docs',
            'chore', 'style', 'perf', 'security', 'unknown'
        )),
    on_task_score   FLOAT       NOT NULL
        CHECK (on_task_score BETWEEN 0.0 AND 1.0),
    raw_response    JSONB,
    latency_ms      INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS change_descriptions_file_change_idx ON change_descriptions (file_change_id);
CREATE INDEX IF NOT EXISTS change_descriptions_workspace_idx   ON change_descriptions (workspace_id);
CREATE INDEX IF NOT EXISTS change_descriptions_created_at_idx  ON change_descriptions (created_at DESC);

COMMENT ON TABLE  change_descriptions                  IS 'Ollama-generated descriptions for each file change.';
COMMENT ON COLUMN change_descriptions.on_task_score    IS '0=completely off-task, 1=perfectly aligned with active task.';
COMMENT ON COLUMN change_descriptions.classification   IS 'Best-fit change type label chosen by the LLM.';

-- ─────────────────────────────────────────────────────────────
-- 5. ALIGNMENT_SNAPSHOTS
--    Rolling history of overall alignment state.
--    One row written per batch processing cycle.
--    Used for the score ring in the sidebar and future charts.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alignment_snapshots (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    task_id       UUID        REFERENCES tasks(id) ON DELETE SET NULL,
    github_user   TEXT        NOT NULL DEFAULT 'aryasentry',
    score         FLOAT       NOT NULL
        CHECK (score BETWEEN 0.0 AND 1.0),
    state         TEXT        NOT NULL
        CHECK (state IN ('aligned', 'mild-drift', 'drift', 'idle', 'paused', 'no-task')),
    files_changed INTEGER     NOT NULL DEFAULT 0,
    computed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS alignment_snapshots_workspace_idx   ON alignment_snapshots (workspace_id);
CREATE INDEX IF NOT EXISTS alignment_snapshots_computed_at_idx ON alignment_snapshots (computed_at DESC);

COMMENT ON TABLE  alignment_snapshots             IS 'Time-series of alignment scores per workspace.';
COMMENT ON COLUMN alignment_snapshots.score       IS 'Aggregate cosine similarity for this batch.';
COMMENT ON COLUMN alignment_snapshots.state       IS 'Derived state label from the score thresholds.';
COMMENT ON COLUMN alignment_snapshots.files_changed IS 'Number of distinct files in the triggering batch.';

-- ─────────────────────────────────────────────────────────────

-- ============================================================
-- 5b. CHANGE_CHUNKS
--    Time-based chunks of file changes for history search.
-- ============================================================
CREATE TABLE IF NOT EXISTS change_chunks (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  UUID        NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    task_id       UUID        REFERENCES tasks(id) ON DELETE SET NULL,
    github_user   TEXT        NOT NULL DEFAULT 'aryasentry',
    start_time    TIMESTAMPTZ NOT NULL,
    end_time      TIMESTAMPTZ NOT NULL,
    summary       TEXT        NOT NULL,
    file_count    INTEGER     NOT NULL DEFAULT 0,
    file_paths    TEXT[]      NOT NULL DEFAULT '{}',
    is_embedded   BOOLEAN     NOT NULL DEFAULT false,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS change_chunks_workspace_idx ON change_chunks (workspace_id);
CREATE INDEX IF NOT EXISTS change_chunks_task_idx      ON change_chunks (task_id);
CREATE INDEX IF NOT EXISTS change_chunks_end_time_idx  ON change_chunks (end_time DESC);

COMMENT ON TABLE change_chunks IS 'Time-based chunk summaries for history search.';

ALTER TABLE file_changes
    ADD COLUMN IF NOT EXISTS chunk_id UUID REFERENCES change_chunks(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────
-- MIGRATIONS — add github_user to existing tables (safe to re-run)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE workspaces          ADD COLUMN IF NOT EXISTS github_user TEXT NOT NULL DEFAULT 'aryasentry';
ALTER TABLE tasks               ADD COLUMN IF NOT EXISTS github_user TEXT NOT NULL DEFAULT 'aryasentry';
ALTER TABLE file_changes        ADD COLUMN IF NOT EXISTS github_user TEXT NOT NULL DEFAULT 'aryasentry';
ALTER TABLE change_descriptions ADD COLUMN IF NOT EXISTS github_user TEXT NOT NULL DEFAULT 'aryasentry';
ALTER TABLE alignment_snapshots ADD COLUMN IF NOT EXISTS github_user TEXT NOT NULL DEFAULT 'aryasentry';
ALTER TABLE change_chunks       ADD COLUMN IF NOT EXISTS github_user TEXT NOT NULL DEFAULT 'aryasentry';

COMMENT ON COLUMN workspaces.github_user          IS 'GitHub username of the developer who owns this workspace.';
COMMENT ON COLUMN tasks.github_user               IS 'GitHub username of the developer who set this task.';
COMMENT ON COLUMN file_changes.github_user        IS 'GitHub username of the developer who made this change.';
COMMENT ON COLUMN change_descriptions.github_user IS 'GitHub username associated with the described change.';
COMMENT ON COLUMN alignment_snapshots.github_user IS 'GitHub username of the developer at snapshot time.';
COMMENT ON COLUMN change_chunks.github_user       IS 'GitHub username of the developer who produced this chunk.';

--    Disable for now (service-role key used by server).
--    Re-enable if you expose Supabase directly to clients.
-- ─────────────────────────────────────────────────────────────
ALTER TABLE workspaces          DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks               DISABLE ROW LEVEL SECURITY;
ALTER TABLE file_changes        DISABLE ROW LEVEL SECURITY;
ALTER TABLE change_descriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE change_chunks        DISABLE ROW LEVEL SECURITY;
ALTER TABLE alignment_snapshots DISABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 7. HELPER VIEWS
-- ─────────────────────────────────────────────────────────────

-- Latest active task per workspace
CREATE OR REPLACE VIEW active_tasks AS
SELECT
    w.path       AS workspace_path,
    w.name       AS workspace_name,
    t.id         AS task_id,
    t.task_key,
    t.description,
    t.created_at
FROM workspaces w
JOIN tasks t ON t.workspace_id = w.id AND t.is_active = true;

COMMENT ON VIEW active_tasks IS 'Convenience view: currently active task per workspace.';

-- Recent descriptions with context (last 100 per workspace)
CREATE OR REPLACE VIEW recent_descriptions AS
SELECT
    cd.id,
    cd.workspace_id,
    cd.task_id,
    fc.file_path,
    fc.change_cycle,
    cd.summary,
    cd.classification,
    cd.on_task_score,
    cd.model,
    cd.latency_ms,
    cd.created_at
FROM change_descriptions cd
JOIN file_changes fc ON fc.id = cd.file_change_id
ORDER BY cd.created_at DESC;

COMMENT ON VIEW recent_descriptions IS 'Last LLM descriptions with file context, newest first.';

-- ─────────────────────────────────────────────────────────────
-- 8. chunks_pending_embedding VIEW
--    Queried by faiss-service/supabase_sync.py to find all
--    sealed chunks that haven't been embedded yet. Using a view
--    keeps the Python code simple and decoupled from the table name.
-- ─────────────────────────────────────────────────────────────
DROP VIEW IF EXISTS chunks_pending_embedding;
CREATE VIEW chunks_pending_embedding AS
SELECT
    id           AS chunk_id,
    workspace_id,
    task_id,
    github_user,
    summary,
    file_paths,
    start_time,
    end_time,
    created_at
FROM change_chunks
WHERE is_embedded = false
ORDER BY created_at ASC;

COMMENT ON VIEW chunks_pending_embedding IS 'Unembedded chunks, consumed by the FAISS sync service.';


-- ============================================================
-- ██████╗  █████╗ ██████╗ ████████╗    ██████╗
-- ██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝    ██╔══██╗
-- ██████╔╝███████║██████╔╝   ██║       ██████╔╝
-- ██╔═══╝ ██╔══██║██╔══██╗   ██║       ██╔══██╗
-- ██║     ██║  ██║██║  ██║   ██║       ██████╔╝
-- ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝       ╚═════╝
-- APPLICATION TABLES (ugie_ prefix — no name collision with CodePolice)
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- SHARED TRIGGER FUNCTION
-- Sets updated_at = now() before any UPDATE.
-- Used by all ugie_ tables that track mutations.
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION ugie_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- ─────────────────────────────────────────────────────────────
-- A1. UGIE_HEALTH_PING
--     Lightweight liveness table for health checks.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_health_ping (
    id SERIAL PRIMARY KEY
);

-- ─────────────────────────────────────────────────────────────
-- A2. UGIE_USERS
--     Authenticated users (GitHub OAuth).
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_users (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    github_id        BIGINT      NOT NULL,
    login            TEXT        NOT NULL,
    email            TEXT,
    avatar_url       TEXT,
    encrypted_token  TEXT,
    token_scopes     TEXT[],
    token_valid      BOOLEAN     DEFAULT true,
    token_checked_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ugie_users_github_id_key UNIQUE (github_id)
);

CREATE INDEX IF NOT EXISTS idx_ugie_users_github_id ON ugie_users USING btree (github_id);

CREATE OR REPLACE TRIGGER trg_ugie_users_updated_at
    BEFORE UPDATE ON ugie_users
    FOR EACH ROW EXECUTE FUNCTION ugie_set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- A3. UGIE_GITHUB_IDENTITIES
--     GitHub identity records (may be resolved to a ugie_user).
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_github_identities (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    github_login  TEXT        NOT NULL,
    github_id     BIGINT      UNIQUE,
    avatar_url    TEXT,
    name          TEXT,
    bio           TEXT,
    company       TEXT,
    location      TEXT,
    site_user_id  UUID        REFERENCES ugie_users(id) ON DELETE SET NULL,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at   TIMESTAMPTZ,

    CONSTRAINT ugie_github_identities_github_login_key UNIQUE (github_login)
);

CREATE INDEX IF NOT EXISTS idx_ugie_github_identities_login
    ON ugie_github_identities USING btree (github_login);
CREATE INDEX IF NOT EXISTS idx_ugie_github_identities_github_id
    ON ugie_github_identities USING btree (github_id) WHERE github_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ugie_github_identities_site_user
    ON ugie_github_identities USING btree (site_user_id) WHERE site_user_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────
-- A4. UGIE_REPOSITORIES
--     GitHub repos tracked per user.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_repositories (
    id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID        NOT NULL REFERENCES ugie_users(id) ON DELETE CASCADE,
    github_id          BIGINT      NOT NULL,
    owner_login        TEXT        NOT NULL,
    name               TEXT        NOT NULL,
    full_name          TEXT        NOT NULL,
    private            BOOLEAN     NOT NULL DEFAULT false,
    archived           BOOLEAN     NOT NULL DEFAULT false,
    default_branch     TEXT        NOT NULL DEFAULT 'main',
    language           TEXT,
    stargazers_count   INTEGER     NOT NULL DEFAULT 0,
    forks_count        INTEGER     NOT NULL DEFAULT 0,
    open_issues_count  INTEGER     NOT NULL DEFAULT 0,
    role               TEXT        NOT NULL DEFAULT 'collaborator',
    webhook_id         BIGINT,
    webhook_active     BOOLEAN     DEFAULT false,
    last_synced_at     TIMESTAMPTZ,
    backfill_cursor    TEXT,
    backfill_complete  BOOLEAN     DEFAULT false,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ugie_repositories_user_id_github_id_key UNIQUE (user_id, github_id)
);

CREATE INDEX IF NOT EXISTS idx_ugie_repos_user_id  ON ugie_repositories USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_ugie_repos_full_name ON ugie_repositories USING btree (full_name);

CREATE OR REPLACE TRIGGER trg_ugie_repositories_updated_at
    BEFORE UPDATE ON ugie_repositories
    FOR EACH ROW EXECUTE FUNCTION ugie_set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- A5. UGIE_COMMITS
--     Individual commits ingested from GitHub.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_commits (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_id        UUID        NOT NULL REFERENCES ugie_repositories(id) ON DELETE CASCADE,
    sha            TEXT        NOT NULL,
    message        TEXT        NOT NULL,
    author_login   TEXT,
    author_email   TEXT,
    authored_at    TIMESTAMPTZ NOT NULL,
    additions      INTEGER     NOT NULL DEFAULT 0,
    deletions      INTEGER     NOT NULL DEFAULT 0,
    files_changed  INTEGER     NOT NULL DEFAULT 0,
    ingested_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    source         TEXT        NOT NULL DEFAULT 'backfill',

    CONSTRAINT ugie_commits_repo_id_sha_key UNIQUE (repo_id, sha)
);

CREATE INDEX IF NOT EXISTS idx_ugie_commits_repo_id     ON ugie_commits USING btree (repo_id);
CREATE INDEX IF NOT EXISTS idx_ugie_commits_authored_at ON ugie_commits USING btree (authored_at DESC);
CREATE INDEX IF NOT EXISTS idx_ugie_commits_author      ON ugie_commits USING btree (author_login);

-- ─────────────────────────────────────────────────────────────
-- A6. UGIE_ISSUES
--     GitHub issues ingested per repo.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_issues (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_id         UUID        NOT NULL REFERENCES ugie_repositories(id) ON DELETE CASCADE,
    number          INTEGER     NOT NULL,
    title           TEXT        NOT NULL,
    state           TEXT        NOT NULL,
    author_login    TEXT,
    assignee_login  TEXT,
    comments_count  INTEGER     NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    closed_at       TIMESTAMPTZ,
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ugie_issues_repo_id_number_key UNIQUE (repo_id, number)
);

CREATE INDEX IF NOT EXISTS idx_ugie_issues_repo_id ON ugie_issues USING btree (repo_id);
CREATE INDEX IF NOT EXISTS idx_ugie_issues_state   ON ugie_issues USING btree (state);

CREATE OR REPLACE TRIGGER trg_ugie_issues_updated_at
    BEFORE UPDATE ON ugie_issues
    FOR EACH ROW EXECUTE FUNCTION ugie_set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- A7. UGIE_WEBHOOK_EVENTS
--     Raw GitHub webhook payloads for async processing.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_webhook_events (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id       TEXT        NOT NULL,
    event_type     TEXT        NOT NULL,
    repo_id        UUID        REFERENCES ugie_repositories(id) ON DELETE SET NULL,
    raw_payload    JSONB       NOT NULL,
    processed      BOOLEAN     NOT NULL DEFAULT false,
    failed         BOOLEAN     NOT NULL DEFAULT false,
    retry_count    INTEGER     NOT NULL DEFAULT 0,
    received_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at   TIMESTAMPTZ,
    error_message  TEXT,

    CONSTRAINT ugie_webhook_events_event_id_key UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_ugie_webhook_events_event_id  ON ugie_webhook_events USING btree (event_id);
CREATE INDEX IF NOT EXISTS idx_ugie_webhook_events_processed ON ugie_webhook_events USING btree (processed);
CREATE INDEX IF NOT EXISTS idx_ugie_webhook_events_failed    ON ugie_webhook_events USING btree (failed);

-- ─────────────────────────────────────────────────────────────
-- A8. UGIE_REPO_COLLABORATORS
--     Who has access to each tracked repo.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_repo_collaborators (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_id              UUID        NOT NULL REFERENCES ugie_repositories(id) ON DELETE CASCADE,
    github_identity_id   UUID        NOT NULL REFERENCES ugie_github_identities(id) ON DELETE CASCADE,
    permission           TEXT        NOT NULL DEFAULT 'read',
    role_name            TEXT,
    fetched_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ugie_repo_collaborators_repo_id_github_identity_id_key
        UNIQUE (repo_id, github_identity_id)
);

CREATE INDEX IF NOT EXISTS idx_ugie_repo_collaborators_repo_id
    ON ugie_repo_collaborators USING btree (repo_id);
CREATE INDEX IF NOT EXISTS idx_ugie_repo_collaborators_identity
    ON ugie_repo_collaborators USING btree (github_identity_id);

-- ─────────────────────────────────────────────────────────────
-- A9. UGIE_CONTRIBUTION_SNAPSHOTS
--     Daily contribution metrics per user per repo.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_contribution_snapshots (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID        NOT NULL REFERENCES ugie_users(id)         ON DELETE CASCADE,
    repo_id        UUID        NOT NULL REFERENCES ugie_repositories(id)  ON DELETE CASCADE,
    snapshot_date  DATE        NOT NULL,
    commit_count   INTEGER     NOT NULL DEFAULT 0,
    additions      INTEGER     NOT NULL DEFAULT 0,
    deletions      INTEGER     NOT NULL DEFAULT 0,
    files_changed  INTEGER     NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ugie_contribution_snapshots_user_id_repo_id_snapshot_date_key
        UNIQUE (user_id, repo_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_ugie_snapshots_user_repo
    ON ugie_contribution_snapshots USING btree (user_id, repo_id);
CREATE INDEX IF NOT EXISTS idx_ugie_snapshots_date
    ON ugie_contribution_snapshots USING btree (snapshot_date DESC);

CREATE OR REPLACE TRIGGER trg_ugie_contribution_snapshots_updated_at
    BEFORE UPDATE ON ugie_contribution_snapshots
    FOR EACH ROW EXECUTE FUNCTION ugie_set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- A10. UGIE_TASKS
--      Project management tasks (board cards).
--      References auth.users (Supabase built-in auth).
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ugie_tasks (
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id              UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
    repo_id              UUID        REFERENCES ugie_repositories(id) ON DELETE SET NULL,
    frontend_project_id  TEXT        NOT NULL,
    title                TEXT        NOT NULL,
    assignee             TEXT,
    priority             TEXT        NOT NULL DEFAULT 'medium',
    deadline             DATE,
    tags                 TEXT[]      NOT NULL DEFAULT '{}',
    status               TEXT        NOT NULL DEFAULT 'todo',
    story_points         INTEGER     NOT NULL DEFAULT 1,
    created_by           TEXT,
    source               TEXT        NOT NULL DEFAULT 'manual',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE TRIGGER trg_ugie_tasks_updated_at
    BEFORE UPDATE ON ugie_tasks
    FOR EACH ROW EXECUTE FUNCTION ugie_set_updated_at();

-- RLS — disabled for now (service-role key)
ALTER TABLE ugie_users                   DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_github_identities       DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_repositories            DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_commits                 DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_issues                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_webhook_events          DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_repo_collaborators      DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_contribution_snapshots  DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_tasks                   DISABLE ROW LEVEL SECURITY;
ALTER TABLE ugie_health_ping             DISABLE ROW LEVEL SECURITY;


-- ============================================================
-- CROSS-SCHEMA LINKS
-- Wire CodePolice extension tables → ugie_ application tables.
-- Migrations: safe to re-run (ADD COLUMN IF NOT EXISTS).
-- ============================================================

-- workspaces: which GitHub repo does this VS Code window track?
ALTER TABLE workspaces
    ADD COLUMN IF NOT EXISTS repo_id             UUID REFERENCES ugie_repositories(id)      ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS github_identity_id  UUID REFERENCES ugie_github_identities(id) ON DELETE SET NULL;

-- tasks: who set this task?
ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS github_identity_id  UUID REFERENCES ugie_github_identities(id) ON DELETE SET NULL;

-- file_changes: who made this change?
ALTER TABLE file_changes
    ADD COLUMN IF NOT EXISTS github_identity_id  UUID REFERENCES ugie_github_identities(id) ON DELETE SET NULL;

-- change_descriptions: attributed to whom?
ALTER TABLE change_descriptions
    ADD COLUMN IF NOT EXISTS github_identity_id  UUID REFERENCES ugie_github_identities(id) ON DELETE SET NULL;

-- alignment_snapshots: snapshot for whom?
ALTER TABLE alignment_snapshots
    ADD COLUMN IF NOT EXISTS github_identity_id  UUID REFERENCES ugie_github_identities(id) ON DELETE SET NULL;

-- change_chunks: chunk produced by whom?
ALTER TABLE change_chunks
    ADD COLUMN IF NOT EXISTS github_identity_id  UUID REFERENCES ugie_github_identities(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS workspaces_repo_id_idx            ON workspaces        (repo_id);
CREATE INDEX IF NOT EXISTS workspaces_identity_idx           ON workspaces        (github_identity_id);
CREATE INDEX IF NOT EXISTS tasks_identity_idx                ON tasks             (github_identity_id);
CREATE INDEX IF NOT EXISTS file_changes_identity_idx         ON file_changes      (github_identity_id);
CREATE INDEX IF NOT EXISTS change_descriptions_identity_idx  ON change_descriptions (github_identity_id);
CREATE INDEX IF NOT EXISTS alignment_snapshots_identity_idx  ON alignment_snapshots (github_identity_id);
CREATE INDEX IF NOT EXISTS change_chunks_identity_idx        ON change_chunks     (github_identity_id);

COMMENT ON COLUMN workspaces.repo_id                   IS 'Optional link to the GitHub repo this workspace tracks (ugie_repositories).';
COMMENT ON COLUMN workspaces.github_identity_id        IS 'Resolved GitHub identity of the workspace owner.';
COMMENT ON COLUMN tasks.github_identity_id             IS 'Resolved GitHub identity of the task setter.';
COMMENT ON COLUMN file_changes.github_identity_id      IS 'Resolved GitHub identity of the developer who made this change.';
COMMENT ON COLUMN change_descriptions.github_identity_id IS 'Resolved GitHub identity for the described change.';
COMMENT ON COLUMN alignment_snapshots.github_identity_id IS 'Resolved GitHub identity at snapshot time.';
COMMENT ON COLUMN change_chunks.github_identity_id     IS 'Resolved GitHub identity who produced this chunk.';


-- ============================================================
-- CROSS-SCHEMA VIEW: developer_activity
-- Joins CodePolice alignment data with ugie commit/repo context.
-- Useful for dashboards: "show all activity for user X in repo Y".
-- ============================================================
CREATE OR REPLACE VIEW developer_activity AS
SELECT
    gi.github_login,
    gi.avatar_url,
    r.full_name          AS repo_full_name,
    w.path               AS workspace_path,
    cd.summary,
    cd.classification,
    cd.on_task_score,
    t.task_key,
    t.description        AS task_description,
    fc.file_path,
    fc.processed_at
FROM change_descriptions cd
JOIN file_changes        fc ON fc.id             = cd.file_change_id
JOIN workspaces          w  ON w.id              = cd.workspace_id
LEFT JOIN tasks          t  ON t.id              = cd.task_id
LEFT JOIN ugie_github_identities gi ON gi.id     = cd.github_identity_id
LEFT JOIN ugie_repositories      r  ON r.id      = w.repo_id
ORDER BY fc.processed_at DESC;

COMMENT ON VIEW developer_activity IS 'Cross-schema view: CodePolice change data enriched with ugie GitHub identity and repo context.';


-- ─────────────────────────────────────────────────────────────
-- DONE
-- ─────────────────────────────────────────────────────────────


